version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: dock-frontend.Dockerfile
    container_name: words-frontend
    ports:
      - "80"
    expose:
      - "80"
    networks:
      - appnet

  api:
    build:
      context: .
      dockerfile: dock-api.Dockerfile
    container_name: words-api
    ports:
      - "5000"
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - appnet

  nginx-api:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge