version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: words-api
    ports:
      - "5000"
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge